# Generated by Django 4.2.7 on 2023-11-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_akari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='imageUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
