# Generated by Django 4.2.6 on 2024-01-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamfinder_api_app', '0007_remove_usersinteams_team_remove_usersinteams_user_and_more'),
        ('tf_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mainGame',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teamfinder_api_app.gameentry'),
        ),
    ]
