# Generated by Django 4.2.7 on 2024-01-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfuser',
            name='username',
        ),
        migrations.AddField(
            model_name='tfuser',
            name='name',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
