# Generated by Django 4.2.7 on 2024-01-03 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamfinder_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reportinguser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportinguser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='targetuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesuggestion',
            name='sentByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
