# Generated by Django 5.0 on 2023-12-29 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamfinder_api_app', '0003_gamesuggestion_team_userreport_usersinteams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='reportingUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportingUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
