# Generated by Django 4.2.7 on 2024-01-01 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamfinder_api_app', '0004_alter_userreport_reportinguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='reportingUser',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='targetUser',
        ),
        migrations.AddField(
            model_name='userreport',
            name='reportinguser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportinguser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='targetuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='targetuser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
