# Generated by Django 4.2.6 on 2024-01-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamfinder_api_app', '0005_remove_userreport_reportinguser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesuggestion',
            name='suggestionCount',
            field=models.IntegerField(default=1),
        ),
    ]
