# Generated by Django 4.2.7 on 2024-01-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamfinder_api_app', '0006_gamesuggestion_suggestioncount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersinteams',
            name='team',
        ),
        migrations.RemoveField(
            model_name='usersinteams',
            name='user',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='UsersInTeams',
        ),
    ]
